[package]
name = "stac-types"
description = "Low-level types for stac-rs. Should not be used directly, usually."
version = "0.1.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
categories.workspace = true
rust-version.workspace = true

[features]
reqwest = ["dep:reqwest"]

[dependencies]
mime.workspace = true
reqwest = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
thiserror.workspace = true
url = { workspace = true, features = ["serde"] }
tracing.workspace = true

[dev-dependencies]
assert-json-diff.workspace = true
stac.workspace = true
