[package]
name = "stac-server"
description = "SpatioTemporal Asset Catalog (STAC) API server"
version = "0.3.4"
keywords = ["geospatial", "stac", "metadata", "geo", "server"]
categories = ["science", "data-structures"]
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
axum = ["dep:axum", "dep:bytes", "dep:mime", "dep:tower-http"]
duckdb = ["dep:stac-duckdb", "dep:bb8"]
pgstac = [
    "dep:bb8",
    "dep:bb8-postgres",
    "dep:pgstac",
    "dep:rustls",
    "dep:tokio-postgres",
    "dep:tokio-postgres-rustls",
]

[dependencies]
axum = { workspace = true, optional = true }
bb8 = { workspace = true, optional = true }
bb8-postgres = { workspace = true, optional = true }
bytes = { workspace = true, optional = true }
http.workspace = true
mime = { workspace = true, optional = true }
pgstac = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
stac.workspace = true
stac-api = { workspace = true, features = ["geo"] }
stac-duckdb = { workspace = true, optional = true }
thiserror.workspace = true
tokio-postgres = { workspace = true, optional = true }
tokio-postgres-rustls = { workspace = true, optional = true }
tower-http = { workspace = true, features = ["cors", "trace"], optional = true }
tracing.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
stac = { workspace = true, features = ["validate"] }
tokio = { workspace = true, features = ["macros"] }
tokio-test.workspace = true
tower = { workspace = true, features = ["util"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
